---
abstract: 'Take old or new Word files and spit out superclean HTML'
author:
  - 'Amiri Barksdale <amiribarksdale@gmail.com>'
build_requires:
  Env::Path: 0
  Module::Find: 0
  Test::Moose: 0
  Test::Most: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MSWord-ToHTML
requires:
  Archive::Zip: 0
  Archive::Zip::MemberRead: 0
  CSS: 0
  Carp: 0
  Cwd: 0
  Digest::SHA1: 0
  Encode: 0
  Encode::Guess: 0
  File::Spec: 0
  HTML::Entities: 0
  HTML::HTML5::Writer: 0
  HTML::TreeBuilder: 0
  IO::All: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Method::Signatures: 0
  MooseX::Types: 0
  MooseX::Types::IO::All: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class::File: 0
  Text::Extract::Word: 0
  Try::Tiny: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  autodie: 0
  feature: 0
  namespace::autoclean: 0
  strictures: 1
resources:
  bugtracker: https://github.com/amiri/MSWord-ToHTML/issues
  repository: git://github.com/amiri/MSWord-ToHTML.git
version: 0.009
